### ISSUE TITLE
Access Violation crash after several scans.

### ISSUE THREAD

**Issue by ArneMayer** [mtaulty/QrCodes#1]
Im using this project in my app to scan qr codes but after several scans the application exits with an access violation error (no exception, just an exit code). Does anyone else have this problem?

**Comment by mtaulty** [comment]
I think I've seen this - haven't had opportunity to debug it to the point of understanding quite where it's coming from yet though I'm afraid.

**Comment by mattfedocsg** [comment]
Yea I am coming across it as well.  I even tried changing the result of the callback to just a string with no luck.  It always happens on the second result, no matter what for me.  Is it maybe due to the time out await?  I made the time out only 5 seconds and removed everything from memory, but that didnt work.  There has to be something that is getting called in memory where it doesnt exist.

**Comment by mattfedocsg** [comment]
`The thread 0x414 has exited with code 0 (0x0).
The thread 0xc60 has exited with code 0 (0x0).
The thread 0x1338 has exited with code 0 (0x0).
Exception thrown: 'System.Exception' in Assembly-CSharp.dll
The program '[2232] Hololens.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.`

**Comment by mtaulty** [comment]
I reworked the code to try and fix this - the solution is perhaps a bit less 'elegant' than it was but I can run many times and I don't see this crash any more.

**Comment by ArneMayer** [comment]
Unfortunately, it doesn't recognize any codes anymore for me.

**Comment by mtaulty** [comment]
Woops - that doesn't sound good. Is this in Unity? in Xaml? In Both?

**Comment by ArneMayer** [comment]
We are using the scanner on the hololens, which is a unity project.

**Comment by mtaulty** [comment]
That's not good. I just cloned down the latest bits. I opened the Unity project. I built the Visual Studio solution. I deployed from Visual Studio to my HoloLens. I scanned the same QR code 10 times one after the other using what I deployed. The QR code was on my 2nd monitor approximately 40-50cm in front of the HoloLens and it's approximately 3cm high and was generated from the QR code generator that you find if you search Bing for QR codes.

So, this seems to be working for me - can you provide more detail or maybe help debug what's happening on your system?

**Comment by ArneMayer** [comment]
I found the problem. It was on my side. Previously, a team member of ours had modified the code to read barcodes instead. Of course, this was gone once I recompiled the code with the latest version of MediaFrameQrProcessing. I wasn't aware that a modification had been necessary for the code to recognize barcodes. Sorry for the confusion. Thank you for fixing the access violation :-)

**Comment by mtaulty** [comment]
No problem - glad that it's been improved by the fix.
