### ISSUE TITLE
Unity doesn't build

### ISSUE THREAD

**Issue by motionsmith** [mtaulty/QrCodes#2]
Hey Mike, thanks for this project. I'm looking at it because I'm interested that you got access to the video camera in C# (I thought it was only doable in C++), and am curious if C# also has access to the frame sample attributes, namely the projection matrix and the transformation matrix for converting image pixel space to Unity's world space.

For starters, I downloaded the repo and tried to compile the Unity project. After switching platforms and configuring HL settings, there are a number of errors. I wonder if you did a clean clone, if you'd find some of these:

1. There are a number of console errors out of the gate related to serialization
2. Scene1>Main Camera has a missing prefab (no indication of what it is).
3. There's a GameObject called Placeholder which has two missing scripts. I'm assuming one of them is the `Placeholder.cs` file but I can't tell what the other one is.
4. Attempting to build the visual studio solution produces an error in the console: `UnityException: Failed to run serialization weaver with command "Temp\StagingArea\Data\Managed\MediaFrameQrProcessing.dll" -pdb -verbose  [...]`

From your blog, you look like a busy guy. I'm not sure if this project is sort of a 'commit and forget' type, but any help you can give in this area is much appreciated. There's a gaping hole in the HL community with regards to easily getting per-frame access to the _locatable_ camera frame data. Once someone writes a clean Unity-compatible library for getting per-frame data in memory, I think there will be a huge amount of potential unleashed for realtime MR CV.

**Comment by motionsmith** [comment]
Update:
The errors I saw in problem #1 (above) have gone away, so they probably only fire during the "project import" setup phase. 

I think problems #2 and #3 are resolved by following the tutorial on your blog, as seen by the screenshots.

However, **problem #4 is still occurring**. This happens when I attempt to make a build from Unity.

**Comment by mtaulty** [comment]
I attempted to fix this - I think one of the .gitignore files was broken here. Maybe pull the repo cleanly again here and see if that resolves?
